version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
  app:
    container_name: app
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo